[package]
name = "pui"
version = "0.1.0"
description = "pUI - packet flow sequence analyzer"
authors = ["xmtlz"]
edition = "2021"

[lib]
name = "pui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
rfd = "0.15"

