/** tshark `-e` 精选字段清单:前后端契约的唯一前端源。
 *  与 src-tauri/src/tshark.rs 的 CAPTURE_FIELDS 保持逐字一致(Rust 侧为权威实现,
 *  scripts/gen-parsed.mjs 与本清单同步);新增字段时三处一起改。
 *  字段名为 tshark -G fields 规范名(下划线);前端解析器同时兼容树形态的连字符键。 */
export const CAPTURE_FIELDS: string[] = [
  'frame.number',
  'frame.time_relative',
  'frame.time_epoch',
  'frame.interface_id',
  'frame.len',
  'frame.protocols',
  'eth.src',
  'eth.dst',
  'ip.src',
  'ip.dst',
  'ipv6.src',
  'ipv6.dst',
  'tcp.srcport',
  'tcp.dstport',
  'tcp.flags',
  'tcp.seq_raw',
  'tcp.ack_raw',
  'tcp.analysis.retransmission',
  'tcp.analysis.fast_retransmission',
  'tcp.analysis.out_of_order',
  'tcp.analysis.duplicate_ack',
  'tcp.analysis.lost_segment',
  'udp.srcport',
  'udp.dstport',
  'http.request.method',
  'http.request.uri',
  'http.response.code',
  'http.time',
  'http.request.line',
  'http.response.line',
  'dns.qry.name',
  'dns.flags.response',
  'tls.handshake.type',
]
